services:
    - docker:dind

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

stages:
    - prepare
    - test
    - analysis
    - build

prepare:
    image: trion/ng-cli-karma:latest
    stage: prepare
    script:
        - npm install --production=false

lint:
    image: trion/ng-cli-karma:latest
    stage: test
    dependencies:
        - prepare
    before_script:
        - npm install -g dockerlint
    script:
        - npm install --production=false
        - npm run lint
        - dockerlint Dockerfile

test:
    image: trion/ng-cli-karma:latest
    stage: test
    dependencies:
        - prepare
    script:
        - npm install --production=false
        - npm run test
    artifacts:
        paths:
            - coverage

sonarqube:
    image: registry.gitlab.com/vincent-p/docker-sonar-runner
    stage: analysis
    dependencies:
        - test
    variables:
        SONAR_URL: https://sonarqube.we-program-it.com
        SONAR_GITLAB_PROJECT_ID: 9193568
        SONAR_ANALYSIS_MODE: publish
    script:
        - npm install --production=false
        - gitlab-sonar-scanner -Dsonar.login=${SONARQUBE_TOKEN}
    allow_failure: true

sast:
    stage: analysis
    image: docker:dind
    variables:
        DOCKER_DRIVER: overlay2
    script:
        - export SAST_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
        - docker run
            --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
            --env SAST_DISABLE_REMOTE_CHECKS="${SAST_DISABLE_REMOTE_CHECKS:-false}"
            --volume "$PWD:/code"
            --volume /var/run/docker.sock:/var/run/docker.sock
            "registry.gitlab.com/gitlab-org/security-products/sast:$SAST_VERSION" /app/bin/run /code
    artifacts:
        paths: [gl-sast-report.json]


build-master:
    image: docker:dind
    stage: build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build --no-cache --pull -t "$CI_REGISTRY_IMAGE" .
        - docker push "$CI_REGISTRY_IMAGE"
    only:
        - master

build:
    image: docker:dind
    stage: build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build --no-cache --build-arg ANGULAR_CONFIGURATION=beta --pull -t "$CI_REGISTRY_IMAGE:beta" .
        - docker push "$CI_REGISTRY_IMAGE:beta"
    except:
        - master
