services:
    - docker:dind

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

stages:
    - test
    - build

test:
    image: trion/ng-cli-karma:latest
    stage: test
    script:
        - yarn install --network-timeout 100000
        - npm run lint
        - npm run test

build-master:
    image: docker:dind
    stage: build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - docker push "$CI_REGISTRY_IMAGE"
    only:
        - master

build:
    image: docker:dind
    stage: build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build --build-arg ANGULAR_CONFIGURATION=beta --pull -t "$CI_REGISTRY_IMAGE:beta" .
        - docker push "$CI_REGISTRY_IMAGE:beta"
    except:
        - master
